language: php

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install

script:
  # check with lock file  
  - ./vendor/bin/phpunit

  # check without lock file  
  - rm composer.lock && rm -rf vendor
  - composer install
  - ./vendor/bin/phpunit

  # integration test
  - composer require php-pm/httpkernel-adapter:dev-master
  - mkdir web && echo Hello > web/index.html
  - bin/ppm start --workers=1 --bridge=StaticBridge --static-directory=web --max-requests=1 -v&
  - while [ ! -f .ppm/run/controller.sock ]; do sleep 1; done
  - bin/ppm status
  - curl -v -f http://127.0.0.1:8080
  - bin/ppm status
  - curl -v -f http://127.0.0.1:8080
  - bin/ppm status

matrix:
  fast_finish: true

# cache vendors
cache:
  directories:
    - $HOME/.composer/cache

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
